version: '3'

services:
  magento:
    image: michielgerritsen/magento-project-community-edition:${PHP_VERSION}-magento${MAGENTO_VERSION}-sample-data
    container_name: magento-project-community-edition
    environment:
      - VIRTUAL_HOST=rvvup.test
    depends_on:
      - nginx-proxy

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./rvvup.test.crt:/etc/nginx/certs/rvvup.test.crt
      - ./rvvup.test.key:/etc/nginx/certs/rvvup.test.key
      - /var/run/docker.sock:/tmp/docker.sock:ro
