name: End 2 End Tests
on:
  pull_request:

jobs:
  end-2-end-tests:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php74-fpm
            MAGENTO_VERSION: 2.4.3
          - PHP_VERSION: php81-fpm
            MAGENTO_VERSION: 2.4.6-p3
          - PHP_VERSION: php82-fpm
            MAGENTO_VERSION: 2.4.6-p3
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ matrix.PHP_VERSION }}
      MAGENTO_VERSION: ${{ matrix.MAGENTO_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Start Docker
        run: |
          openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes -keyout .github/workflows/templates/rvvup.test.key -out .github/workflows/templates/rvvup.test.crt -subj "/CN=rvvup.test" -addext "subjectAltName=DNS:rvvup.test,DNS:localhost,IP:127.0.0.1"
          sudo echo "127.0.0.1 rvvup.test" | sudo tee -a /etc/hosts
          docker-compose -f .github/workflows/templates/docker-compose.end-2-end.yml up -d

      - name: Trust self-signed certificate
        run: |
          sudo mkdir -p /usr/local/share/ca-certificates/extra
          sudo cp .github/workflows/templates/rvvup.test.crt /usr/local/share/ca-certificates/extra/rvvup.test.crt
          sudo update-ca-certificates

      - name: Install Hyvä & prepare Magento
        run: |
          docker exec magento-project-community-edition sh -c "mkdir -p ~/.ssh/ && echo \"${{ secrets.SSH_PRIVATE_KEY }}\" > ~/.ssh/id_ed25519"
          docker exec magento-project-community-edition sh -c "chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519"
          docker exec magento-project-community-edition sh -c "ssh-keyscan -t rsa gitlab.hyva.io >> ~/.ssh/known_hosts"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/magento2-theme-module git git@gitlab.hyva.io:hyva-themes/magento2-theme-module.git"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/magento2-reset-theme git git@gitlab.hyva.io:hyva-themes/magento2-reset-theme.git"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/magento2-email-module git git@gitlab.hyva.io:hyva-themes/magento2-email-module.git"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/magento2-default-theme git git@gitlab.hyva.io:hyva-themes/magento2-default-theme.git"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/magento2-compat-module-fallback git git@gitlab.hyva.io:hyva-themes/magento2-compat-module-fallback.git"
          docker exec magento-project-community-edition ./retry "composer config repositories.hyva-themes/hyva-checkout git git@gitlab.hyva.io:hyva-checkout/checkout.git"
          docker exec magento-project-community-edition ./retry "composer require hyva-themes/magento2-default-theme hyva-themes/magento2-hyva-checkout"
          docker exec magento-project-community-edition ./retry "bin/magento setup:upgrade"

          HYVA_ID=$(docker exec magento-project-community-edition sh -c "magerun2 dev:theme:list --format=json --skip-root-check | jq -r '.[] | select(.code == \"Hyva\\/default\") | .id'")
          echo "Hyvä has theme ID $HYVA_ID"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set design/theme/theme_id $HYVA_ID --scope=stores --scope-id=1"
          docker exec magento-project-community-edition /bin/bash ./change-base-url https://rvvup.test/
          docker exec magento-project-community-edition ./retry "bin/magento cache:flush"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set hyva_themes_checkout/general/checkout default"

          docker exec magento-project-community-edition ./retry "npm --prefix vendor/hyva-themes/magento2-default-theme/web/tailwind/ ci"
          docker exec magento-project-community-edition ./retry "npm --prefix vendor/hyva-themes/magento2-default-theme/web/tailwind/ run build-prod"

      - name: Install the extension
        run: |
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set currency/options/base GBP"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set currency/options/default GBP"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set currency/options/allow GBP"

          docker cp $(pwd) magento-project-community-edition:/data/extensions/
          docker exec magento-project-community-edition composer require --no-plugins --no-interaction rvvup/module-magento-payments-hyva-checkout:@dev
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set payment/rvvup/active 1"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set payment/rvvup/debug 1"
          docker exec magento-project-community-edition ./retry "magerun2 config:store:set payment/rvvup/jwt ${{ secrets.RVVUP_API_KEY }} --encrypt"
          docker exec magento-project-community-edition ./retry "bin/magento cache:flush"
          docker exec magento-project-community-edition ./retry "bin/magento setup:upgrade"

          docker exec magento-project-community-edition ls -al /data/vendor/rvvup/
          docker exec magento-project-community-edition cat /data/vendor/rvvup/module-magento-payments-hyva-checkout/src/view/frontend/templates/product/view/addtocart.phtml
          docker exec magento-project-community-edition cat app/etc/hyva-themes.json

      - name: Check webserver
        run: curl --fail-with-body -vvv https://rvvup.test/

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: BASE_URL=https://rvvup.test/ npx playwright test

      - name: Dump docker-compose logs
        if: always()
        run: |
          mkdir -p var/log
          docker-compose -f .github/workflows/templates/docker-compose.end-2-end.yml logs magento > magento.log
          docker-compose -f .github/workflows/templates/docker-compose.end-2-end.yml logs nginx-proxy > nginx-proxy.log
          docker cp magento-project-community-edition:/data/var/log var/log

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.PHP_VERSION }}-${{ matrix.MAGENTO_VERSION }}-${{ github.run_number }}
          path: |
            playwright-report/
            var/log/
            magento.log
            nginx-proxy.log
